import animate from "tailwindcss-animate";

export default {
  content: ["./index.html", "./src/**/*.{ts,tsx}"],
  theme: {
    extend: {
      fontFamily: {
        display: ["Georgia", "Times New Roman", "serif"],
        sans: ["Inter", "system-ui", "sans-serif"],
        mono: ["JetBrains Mono", "ui-monospace", "monospace"],
      },
      colors: {
        background: "rgb(var(--background) / <alpha-value>)",
        sidebar: "rgb(var(--sidebar) / <alpha-value>)",
        surface: "rgb(var(--surface) / <alpha-value>)",
        "surface-elevated": "rgb(var(--surface-elevated) / <alpha-value>)",
        ink: "rgb(var(--background) / <alpha-value>)",
        graphite: "rgb(var(--sidebar) / <alpha-value>)",
        carbon: "rgb(var(--surface) / <alpha-value>)",
        steel: "rgb(var(--sidebar) / <alpha-value>)",
        paper: "rgb(var(--text-secondary) / <alpha-value>)",
        bone: "rgb(var(--text-primary) / <alpha-value>)",
        accent: "rgb(var(--accent) / <alpha-value>)",
        "accent-hover": "rgb(var(--accent-hover) / <alpha-value>)",
        "accent-soft": "rgb(var(--accent-soft) / <alpha-value>)",
        muted: "rgb(var(--text-muted) / <alpha-value>)",
        border: "rgb(var(--border) / <alpha-value>)",
      },
      spacing: {
        "4.5": "1.125rem",
        "18": "4.5rem",
        "22": "5.5rem",
        "30": "7.5rem",
        "34": "8.5rem",
        "88": "22rem",
        "100": "25rem",
        "120": "30rem",
      },
      fontSize: {
        "2xs": ["0.625rem", { lineHeight: "1rem", letterSpacing: "0.02em" }],
        xs: ["0.75rem", { lineHeight: "1.125rem", letterSpacing: "0.01em" }],
        sm: ["0.8125rem", { lineHeight: "1.375rem", letterSpacing: "0em" }],
        base: ["0.9375rem", { lineHeight: "1.625rem", letterSpacing: "-0.006em" }],
        lg: ["1.0625rem", { lineHeight: "1.75rem", letterSpacing: "-0.011em" }],
        xl: ["1.25rem", { lineHeight: "1.875rem", letterSpacing: "-0.014em" }],
        "2xl": ["1.5rem", { lineHeight: "2.125rem", letterSpacing: "-0.017em" }],
        "3xl": ["1.875rem", { lineHeight: "2.5rem", letterSpacing: "-0.02em" }],
        "4xl": ["2.25rem", { lineHeight: "2.875rem", letterSpacing: "-0.025em" }],
        "5xl": ["3rem", { lineHeight: "3.5rem", letterSpacing: "-0.03em" }],
        "6xl": ["3.75rem", { lineHeight: "4.125rem", letterSpacing: "-0.035em" }],
        "7xl": ["4.5rem", { lineHeight: "4.75rem", letterSpacing: "-0.04em" }],
        "8xl": ["6rem", { lineHeight: "6.125rem", letterSpacing: "-0.045em" }],
        "9xl": ["8rem", { lineHeight: "7.875rem", letterSpacing: "-0.05em" }],
        display: ["5.5rem", { lineHeight: "5.625rem", letterSpacing: "-0.04em" }],
      },
      letterSpacing: {
        tightest: "-0.06em",
        tighter: "-0.04em",
        tight: "-0.02em",
        wide: "0.02em",
        wider: "0.08em",
        widest: "0.15em",
        ultra: "0.25em",
        super: "0.35em",
      },
      borderRadius: {
        "2xs": "2px",
        xs: "4px",
        sm: "6px",
        DEFAULT: "8px",
        md: "12px",
        lg: "16px",
      },
      boxShadow: {
        premium: "0 1px 3px rgba(0,0,0,.08), 0 1px 2px rgba(0,0,0,.04)",
        "premium-lg": "0 4px 16px rgba(0,0,0,.08), 0 2px 4px rgba(0,0,0,.04)",
        glow: "0 1px 4px rgba(0,0,0,.04), 0 0 1px rgba(0,0,0,.08)",
        "glow-sm": "0 1px 2px rgba(0,0,0,.04)",
        button: "0 1px 2px rgba(0,0,0,.06)",
        dock: "0 8px 32px rgba(0,0,0,0.10), 0 2px 8px rgba(0,0,0,0.06)",
      },
      keyframes: {
        "fade-in": { from: { opacity: "0" }, to: { opacity: "1" } },
        "fade-in-up": { from: { opacity: "0", transform: "translateY(12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-in-down": { from: { opacity: "0", transform: "translateY(-12px)" }, to: { opacity: "1", transform: "translateY(0)" } },
        "fade-in-left": { from: { opacity: "0", transform: "translateX(-12px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        "fade-in-right": { from: { opacity: "0", transform: "translateX(12px)" }, to: { opacity: "1", transform: "translateX(0)" } },
        "scale-in": { from: { opacity: "0", transform: "scale(0.96)" }, to: { opacity: "1", transform: "scale(1)" } },
        "slide-up": { from: { transform: "translateY(100%)" }, to: { transform: "translateY(0)" } },
        "slide-down": { from: { transform: "translateY(-100%)" }, to: { transform: "translateY(0)" } },
        "spin-slow": { from: { transform: "rotate(0deg)" }, to: { transform: "rotate(360deg)" } },
        "pulse-soft": { "0%, 100%": { opacity: "0.4" }, "50%": { opacity: "0.8" } },
        float: {
          "0%, 100%": { transform: "translateY(0) rotate(0deg)" },
          "25%": { transform: "translateY(-8px) rotate(2deg)" },
          "50%": { transform: "translateY(4px) rotate(-1deg)" },
          "75%": { transform: "translateY(-4px) rotate(1deg)" },
        },
      },
      animation: {
        "fade-in": "fade-in 0.25s ease-out",
        "fade-in-up": "fade-in-up 0.35s ease-out",
        "fade-in-down": "fade-in-down 0.35s ease-out",
        "fade-in-left": "fade-in-left 0.35s ease-out",
        "fade-in-right": "fade-in-right 0.35s ease-out",
        "scale-in": "scale-in 0.3s ease-out",
        "spin-slow": "spin-slow 18s linear infinite",
        "pulse-soft": "pulse-soft 4s ease-in-out infinite",
        float: "float 6s ease-in-out infinite",
      },
    },
  },
  plugins: [animate],
};
