import type { SubjectProfile } from "../types";

export const artificialIntelligenceProfile: SubjectProfile = {
  id: "artificial-intelligence",
  name: "Artificial Intelligence",
  description: "The field of creating intelligent systems, including machine learning, deep learning, neural networks, and cognitive computing.",
  keywords: [
    "machine learning", "deep learning", "neural network", "ai", "artificial intelligence",
    "supervised learning", "unsupervised learning", "reinforcement learning",
    "classification", "regression", "clustering", "dimensionality reduction",
    "cnn", "rnn", "transformer", "attention", "lstm", "gan",
    "natural language processing", "nlp", "computer vision", "speech recognition",
    "optimization", "gradient descent", "backpropagation", "loss function",
    "activation function", "convolution", "pooling", "embedding", "tokenization",
    "overfitting", "underfitting", "regularization", "dropout", "batch normalization",
    "training", "inference", "fine-tuning", "transfer learning", "dataset",
    "feature engineering", "hyperparameter", "cross-validation", "confusion matrix",
    "precision", "recall", "f1 score", "auc", "roc curve",
    "llm", "large language model", "prompt engineering", "rag", "agent",
    "diffusion model", "transformer architecture", "self-attention",
  ],
  subdisciplines: [
    "machine learning", "deep learning", "natural language processing",
    "computer vision", "reinforcement learning", "generative ai",
    "robotics", "expert systems", "knowledge representation",
    "planning", "search algorithms", "bayesian inference",
    "evolutionary computation", "fuzzy logic",
  ],
  teachingPhilosophy: {
    coreBelief: "AI should be taught by building from first principles — starting with why machines can learn, then how, then what they can do.",
    explanationOrder: [
      "Define intelligence in operational terms",
      "Explain the learning paradigm (supervised, unsupervised, reinforcement)",
      "Build intuition with a simple analogical example",
      "Show the math at a conceptual level",
      "Present the architecture visually",
      "Walk through training step by step",
      "Discuss failure modes and limitations",
      "Show real-world applications and ethical considerations",
    ],
    preferredExamples: [
      "Email spam classification for supervised learning",
      "Customer segmentation for unsupervised learning",
      "Game-playing for reinforcement learning",
      "Image recognition for computer vision",
      "Chat translation for NLP",
      "Recommendation systems for collaborative filtering",
    ],
    preferredAnalogies: [
      "Learning as curve-fitting: finding the right line through data points",
      "Neural networks as cascading functions: each layer transforms the input",
      "Gradient descent as a hiker finding the valley floor in fog",
      "Attention mechanism as a spotlight that highlights relevant information",
      "Training as practice: each example is like a mock exam question",
      "Overfitting as memorizing answers instead of understanding the subject",
    ],
    difficultyProgression: [
      "What problem does AI solve?",
      "How does a machine learn from examples?",
      "What makes a good model?",
      "How do neural networks actually work?",
      "How do we make models better and more efficient?",
      "What are the limits of current AI?",
    ],
    responseStructure: [
      "Big Picture: what this AI technique does and why it matters",
      "Intuition: a mental model through analogy",
      "Core Explanation: how it works technically",
      "Worked Example: applying it to a concrete problem",
      "Visual Thinking: describe the architecture or flow",
      "Common Mistakes: pitfalls and misconceptions",
      "Memory Trick: remember the key idea",
      "Real World Applications: where it is used today",
      "Challenge Question: test understanding",
      "Summary: five key takeaways",
    ],
    importantTerminology: [
      "model: the mathematical representation learned from data",
      "training: the process of adjusting parameters to minimize error",
      "inference: using a trained model to make predictions",
      "feature: an individual measurable property of the data",
      "label: the correct output for supervised learning",
      "loss: a measure of how wrong the model's predictions are",
      "gradient: the direction of steepest increase in the loss function",
      "epoch: one complete pass through the entire training dataset",
    ],
    commonMisconceptions: [
      "AI systems do not 'understand' — they pattern-match statistically",
      "More data does not always mean better models (quality matters more)",
      "Neural networks are not black boxes — every layer has a mathematical interpretation",
      "AI cannot solve problems it has never seen examples of (generalization is limited)",
      "Training and inference are fundamentally different processes",
    ],
    visualStrategy: "Use flow diagrams for model architectures (input → layers → output), loss curves for training progress, confusion matrices for classification results, scatter plots for understanding data distributions, and network graphs for attention patterns. For neural networks, draw the layered structure with input flowing left to right.",
    practiceStrategy: "Start by running existing models and observing their behavior. Progress to modifying hyperparameters and observing effects. Then implement simple algorithms from scratch. Finally, design solutions for novel problems. Use online platforms with instant feedback for practice.",
    revisionStrategy: "Review by model family (linear models, tree-based, neural). Re-implement core algorithms from memory. Compare and contrast different approaches to the same problem. Read and critique research papers. Build end-to-end projects combining multiple AI techniques.",
  },
};
