import type { SubjectProfile } from "../types";

export const businessProfile: SubjectProfile = {
  id: "business",
  name: "Business",
  description: "The study of organizing, managing, and growing enterprises through strategy, operations, marketing, finance, and leadership.",
  keywords: [
    "business", "management", "strategy", "marketing", "operations", "supply chain",
    "leadership", "entrepreneurship", "startup", "innovation", "disruption",
    "competitive advantage", "value proposition", "business model", "revenue",
    "profit", "margin", "cost", "pricing", "market", "segment", "audience",
    "brand", "positioning", "differentiation", "customer acquisition",
    "retention", "lifetime value", "conversion", "funnel", "pipeline",
    "swot analysis", "pest analysis", "porter five forces", "balanced scorecard",
    "kpi", "metric", "okr", "performance", "growth", "scaling",
    "b2b", "b2c", "saas", "subscription", "marketplace", "platform",
    "stakeholder", "corporate governance", "board", "ceo", "executive",
    "organizational structure", "culture", "change management", "agile",
    "negotiation", "sales", "distribution", "channel", "partnership",
  ],
  subdisciplines: [
    "strategic management", "marketing", "operations management",
    "entrepreneurship", "organizational behavior", "human resources",
    "supply chain management", "business analytics", "international business",
    "business ethics", "corporate strategy", "innovation management",
  ],
  teachingPhilosophy: {
    coreBelief: "Business should be taught through real companies making real decisions in real markets — theory is always grounded in practical cases.",
    explanationOrder: [
      "Identify the business problem or opportunity",
      "Present a real company that faced this situation",
      "Explain the strategic options available",
      "Analyze the tradeoffs of each option",
      "Show what the company actually did and the outcome",
      "Generalize the principle to other contexts",
      "Discuss how you would apply this as a manager",
    ],
    preferredExamples: [
      "Apple for product strategy and brand building",
      "Netflix for business model innovation and pivoting",
      "Amazon for operations and customer obsession",
      "Nike for marketing and brand positioning",
      "Toyota for operations and quality management",
      "Tesla for disruptive innovation and vertical integration",
      "Patagonia for values-driven business",
    ],
    preferredAnalogies: [
      "Business strategy as chess: thinking several moves ahead",
      "Marketing as dating: attracting, engaging, and retaining",
      "Operations as a kitchen: coordinating many inputs into a consistent output",
      "Cash flow as blood flow: essential for survival, not just profitability",
      "Culture as the operating system of a company",
    ],
    difficultyProgression: [
      "What does this business function do?",
      "How does it create value?",
      "How do you measure success?",
      "What tradeoffs and decisions does a manager face?",
      "How does this function interact with others?",
      "How do you build a competitive advantage through this?",
    ],
    responseStructure: [
      "Big Picture: the business concept and why it matters",
      "Intuition: a real company example that illustrates it",
      "Core Explanation: the frameworks and principles",
      "Worked Example: applying the framework to a case",
      "Visual Thinking: strategy maps, matrices, or frameworks",
      "Common Mistakes: what managers get wrong",
      "Memory Trick: the key framework or mental model",
      "Real World Applications: how companies use this today",
      "Challenge Question: a strategic decision to analyze",
      "Summary: five key principles",
    ],
    importantTerminology: [
      "value proposition: the unique value a company promises to deliver",
      "competitive advantage: a condition that enables a company to outperform rivals",
      "moat: a sustainable competitive advantage that protects market position",
      "unit economics: revenue and cost per customer or transaction",
      "scalability: the ability to grow without proportional increase in costs",
      "market fit: the degree to which a product satisfies market demand",
      "flywheel: a virtuous cycle where each success feeds the next",
      "tradeoff: choosing one thing over another (strategy is about what NOT to do)",
    ],
    commonMisconceptions: [
      "Profit is not the same as cash flow (a company can be profitable but run out of cash)",
      "Revenue is vanity, profit is sanity, cash is reality",
      "A great product does not guarantee business success",
      "Strategy is not about doing everything well — it is about choosing what NOT to do",
      "Culture is not a perk — it is a performance driver",
    ],
    visualStrategy: "Use strategy maps (Porter's Five Forces, SWOT matrix, Business Model Canvas), process flows for operations, organization charts for structure, growth curves for scaling, dashboards for KPIs, and comparison tables for competitive analysis. Always show how the framework applies to real companies.",
    practiceStrategy: "Analyze real companies using the frameworks taught. Write case study analyses before reading the actual outcome. Calculate and interpret business metrics from financial statements. Role-play management decisions. Present recommendations and defend them.",
    revisionStrategy: "Create a personal toolkit of frameworks. Review by comparing companies in the same industry. Practice applying multiple frameworks to the same case. Stay current with business news and analyze companies in real-time. Build a mental library of business cases and their lessons.",
  },
};
