import type { SubjectProfile } from "../types";

export const computerScienceProfile: SubjectProfile = {
  id: "computer-science",
  name: "Computer Science",
  description: "The study of computation, algorithms, data structures, software systems, and the principles underlying computing.",
  keywords: [
    "programming", "algorithm", "data structure", "software", "code", "function",
    "variable", "class", "object", "array", "loop", "recursion", "sorting",
    "searching", "tree", "graph", "hash", "stack", "queue", "complexity",
    "runtime", "database", "sql", "api", "compiler", "operating system",
    "network", "protocol", "thread", "process", "memory", "garbage collection",
    "design pattern", "architecture", "framework", "library", "dependency",
    "git", "debugging", "testing", "deployment", "ci/cd", "docker",
    "functional programming", "object oriented", "imperative", "declarative",
    "syntax", "type system", "async", "promise", "callback", "event loop",
    "binary", "bit", "byte", "encoding", "compression", "encryption",
  ],
  subdisciplines: [
    "algorithms", "data structures", "software engineering", "programming languages",
    "databases", "networking", "operating systems", "computer architecture",
    "compiler design", "distributed systems", "cybersecurity", "computer graphics",
    "human-computer interaction", "formal methods", "computational theory",
  ],
  teachingPhilosophy: {
    coreBelief: "Computer science must be taught by building intuition before syntax, showing concepts before code, and connecting theory to real engineering practice.",
    explanationOrder: [
      "Start with the problem the concept solves",
      "Build intuition through everyday analogies",
      "Show a visual or diagram of how it works",
      "Introduce terminology after understanding",
      "Present code only after the concept is clear",
      "Walk through a complete working example line by line",
      "Analyze complexity and trade-offs",
      "Show common mistakes and debugging strategies",
      "Connect to real software engineering practice",
    ],
    preferredExamples: [
      "Real-world applications the student already uses",
      "Everyday analogies (filing cabinets for databases, kitchen for operating systems)",
      "Before-and-after examples showing the problem and the solution",
      "Minimal working examples that isolate one concept",
      "Gradually increasing complexity",
    ],
    preferredAnalogies: [
      "Kitchen and recipes for programs and algorithms",
      "Filing cabinet for data structures",
      "Factory assembly line for pipelines and streams",
      "Library catalog for indexing and search",
      "Postal system for networking protocols",
      "Blueprint for architecture and design patterns",
    ],
    difficultyProgression: [
      "What problem does this solve?",
      "How would you explain it to a non-programmer?",
      "What is the simplest possible implementation?",
      "What are the trade-offs and alternatives?",
      "How does this scale?",
      "How is this used in production systems?",
    ],
    responseStructure: [
      "Big Picture: the problem and why it matters",
      "Intuition: everyday analogy or mental model",
      "Core Explanation: precise technical explanation",
      "Worked Example: step-by-step implementation",
      "Visual Thinking: describe the flow or structure",
      "Common Mistakes: what beginners get wrong",
      "Memory Trick: mnemonic or mental hook",
      "Real World Applications: where this is used",
      "Challenge Question: test understanding",
      "Summary: five key takeaways",
    ],
    importantTerminology: [
      "abstraction: hiding complexity behind a clean interface",
      "complexity: how resource usage grows with input size",
      "encapsulation: bundling data with the code that operates on it",
      "polymorphism: one interface, many implementations",
      "recursion: a function that calls itself",
      "idempotence: multiple identical calls produce the same result",
      "state: stored information that can change over time",
      "side effect: any change outside a function's local scope",
    ],
    commonMisconceptions: [
      "Confusing declaration with assignment",
      "Thinking recursion is always slower (it can be clearer and equally fast with tail optimization)",
      "Believing more code equals better code",
      "Confusing OOP with classes (OOP is a paradigm, not a language feature)",
      "Assuming the computer understands high-level abstractions directly",
      "Thinking 'production-ready' means no bugs",
    ],
    visualStrategy: "Use flowcharts for algorithms, box-and-arrow diagrams for memory, tree diagrams for hierarchical structures, network graphs for relationships, and before/after diagrams for transformations. Always describe what each part represents and how data moves through the system.",
    practiceStrategy: "After each concept, provide a minimal exercise that requires applying the concept. Gradually increase complexity. Encourage tracing through code by hand. Use the 'rubber duck' method: explain the code aloud. Build projects that incrementally add features.",
    revisionStrategy: "Review by category (data structures, algorithms, systems). Implement each data structure from scratch. Solve increasingly difficult problems. Teach concepts to others. Re-implement previous projects with better architecture.",
  },
};
