import type { SubjectProfile } from "../types";

export const economicsProfile: SubjectProfile = {
  id: "economics",
  name: "Economics",
  description: "The study of how societies allocate scarce resources to produce, distribute, and consume goods and services.",
  keywords: [
    "economics", "economy", "supply", "demand", "market", "price", "equilibrium",
    "elasticity", "utility", "marginal", "opportunity cost", "scarcity",
    "gdp", "inflation", "unemployment", "recession", "depression",
    "fiscal policy", "monetary policy", "taxation", "government spending",
    "interest rate", "exchange rate", "trade", "tariff", "quota", "globalization",
    "comparative advantage", "absolute advantage", "specialization",
    "monopoly", "oligopoly", "perfect competition", "monopolistic competition",
    "externalities", "public goods", "market failure", "regulation",
    "keynesian", "monetarist", "classical", "behavioral economics",
    "game theory", "nash equilibrium", "prisoner's dilemma", "incentives",
    "consumer surplus", "producer surplus", "deadweight loss",
    "aggregate demand", "aggregate supply", "business cycle",
    "microeconomics", "macroeconomics", "econometrics",
  ],
  subdisciplines: [
    "microeconomics", "macroeconomics", "econometrics",
    "behavioral economics", "development economics", "labor economics",
    "international economics", "public economics", "environmental economics",
    "industrial organization", "financial economics", "economic history",
  ],
  teachingPhilosophy: {
    coreBelief: "Economics should be taught through the lens of incentives and tradeoffs — showing how individual decisions aggregate into system-level outcomes.",
    explanationOrder: [
      "Start with a real-world economic puzzle or observation",
      "Identify the incentives at play",
      "Introduce the model with simplifying assumptions",
      "Show how the model explains the observation",
      "Add realism by relaxing assumptions",
      "Discuss policy implications and debates",
      "Connect to historical or current events",
    ],
    preferredExamples: [
      "Gas prices during hurricanes for supply and demand",
      "Minimum wage debates for price floors",
      "Rent control for price ceilings",
      "Traffic congestion for externalities",
      "Online marketplaces (Uber, Airbnb) for market design",
      "The Great Depression for macroeconomics",
    ],
    preferredAnalogies: [
      "The invisible hand as a flock of birds: individual actions create collective order",
      "Supply and demand as a dance: prices balance what people want with what producers provide",
      "Opportunity cost as the road not taken in every decision",
      "Inflation as a rising tide that lifts all boats but erodes fixed values",
      "Comparative advantage as specialization: do what you do best, trade for the rest",
    ],
    difficultyProgression: [
      "What economic observation does this explain?",
      "What are the key incentives involved?",
      "What does the basic model predict?",
      "What happens when we add real-world complexity?",
      "What are the policy implications?",
      "What do economists disagree about?",
    ],
    responseStructure: [
      "Big Picture: the economic concept and why it shapes our world",
      "Intuition: a real-life situation that illustrates the idea",
      "Core Explanation: the model with assumptions",
      "Worked Example: applying the model to data or a scenario",
      "Visual Thinking: graphs, curves, or tables",
      "Common Mistakes: errors in economic reasoning",
      "Memory Trick: remember the core insight",
      "Real World Applications: current events and policy debates",
      "Challenge Question: analyze a real economic situation",
      "Summary: five key principles",
    ],
    importantTerminology: [
      "opportunity cost: the value of what you give up when you make a choice",
      "marginal analysis: comparing the additional benefit to the additional cost",
      "elasticity: how much quantity changes when price changes",
      "externality: a cost or benefit that affects someone not involved in the transaction",
      "moral hazard: taking more risk because someone else bears the cost",
      "adverse selection: bad products are more likely to be offered when buyers cannot tell quality",
      "comparative advantage: producing goods at a lower opportunity cost than trading partners",
      "liquidity trap: when interest rates are so low that monetary policy loses effectiveness",
    ],
    commonMisconceptions: [
      "Correlation does not imply causation in economics just as in statistics",
      "Markets are not always efficient — information asymmetries and externalities cause failures",
      "GDP is not a measure of well-being, it is a measure of economic output",
      "Trade deficits are not inherently bad (they reflect investment and consumption choices)",
      "Economic models are simplifications — their value is in the insights, not the assumptions",
    ],
    visualStrategy: "Use supply and demand graphs for market analysis, production possibility frontiers for tradeoffs, Lorenz curves for inequality, business cycle graphs for macroeconomics, Phillips curves for inflation-unemployment tradeoffs, and circular flow diagrams for the economy. Always explain the axes and what shifts curves mean.",
    practiceStrategy: "Draw supply and demand graphs for every scenario. Calculate elasticities from data. Identify opportunity costs in everyday decisions. Read and critique economic news articles. Use economic reasoning to analyze policy proposals before reading expert opinions.",
    revisionStrategy: "Review by comparing schools of thought (Keynesian vs. Classical). Create a mental framework connecting micro and macro concepts. Stay current with economic indicators. Apply economic reasoning to non-economic decisions. Teach concepts to others to solidify understanding.",
  },
};
