import type { SubjectProfile } from "../types";

export const engineeringProfile: SubjectProfile = {
  id: "engineering",
  name: "Engineering",
  description: "The application of scientific and mathematical principles to design, build, and optimize structures, machines, systems, and processes.",
  keywords: [
    "engineering", "engineer", "design", "analysis", "mechanics", "thermodynamics",
    "fluid dynamics", "materials science", "structural analysis", "circuit",
    "signal processing", "control system", "robotics", "automation",
    "mechanical engineering", "electrical engineering", "civil engineering",
    "chemical engineering", "aerospace engineering", "biomedical engineering",
    "load", "stress", "strain", "fatigue", "failure", "factor of safety",
    "voltage", "current", "resistance", "capacitance", "inductance",
    "power", "energy", "efficiency", "conservation", "entropy",
    "kinematics", "dynamics", "statics", "equilibrium", "free body diagram",
    "process", "flow", "pressure", "temperature", "heat transfer",
    "system", "feedback", "stability", "transfer function", "frequency response",
    "optimization", "constraint", "tradeoff", "prototype", "testing",
    "cad", "simulation", "modeling", "finite element analysis", "cfd",
    "standard", "code", "regulation", "safety", "reliability",
  ],
  subdisciplines: [
    "mechanical engineering", "electrical engineering", "civil engineering",
    "chemical engineering", "aerospace engineering", "biomedical engineering",
    "computer engineering", "environmental engineering", "industrial engineering",
    "materials engineering", "nuclear engineering", "engineering management",
  ],
  teachingPhilosophy: {
    coreBelief: "Engineering should be taught through design and analysis — understanding why things work, how they fail, and how to make them better.",
    explanationOrder: [
      "State the engineering problem or requirement",
      "Build physical intuition with a real-world example",
      "Introduce the governing principles and equations",
      "Work through an analysis step by step",
      "Discuss design implications and tradeoffs",
      "Consider failure modes and safety factors",
      "Show how professionals apply this in practice",
    ],
    preferredExamples: [
      "Bridges for structural analysis and load distribution",
      "Smartphone for electrical engineering and systems integration",
      "Aircraft wings for aerodynamics and materials",
      "Power plants for thermodynamics and energy systems",
      "Suspension systems for mechanical design and control",
      "Water treatment for chemical and environmental engineering",
    ],
    preferredAnalogies: [
      "Stress and strain as stretching a rubber band",
      "Electrical circuits as water flowing through pipes",
      "Heat transfer as a cup of coffee cooling down",
      "Control systems as a thermostat maintaining temperature",
      "Structures as a skeleton supporting loads",
      "Feedback loops as a speaker microphone causing a screech",
    ],
    difficultyProgression: [
      "What problem does this engineering principle solve?",
      "How does it work in simple physical terms?",
      "What equations describe it and what does each term mean?",
      "How do you apply the equations to a real design?",
      "What are the practical limitations and tradeoffs?",
      "How do you optimize and ensure reliability?",
    ],
    responseStructure: [
      "Big Picture: the engineering concept and why it matters",
      "Intuition: physical analogy or everyday example",
      "Core Explanation: the principles and equations",
      "Worked Example: solve a real engineering problem",
      "Visual Thinking: diagrams, graphs, or schematics",
      "Common Mistakes: design errors and misconceptions",
      "Memory Trick: key equations and heuristics",
      "Real World Applications: how it is used in industry",
      "Challenge Question: an engineering analysis problem",
      "Summary: five key engineering principles",
    ],
    importantTerminology: [
      "factor of safety: how much stronger a design is than the minimum required strength",
      "stress: internal force per unit area within a material",
      "strain: deformation per unit length caused by stress",
      "feedback: using output of a system to control its input",
      "steady state: condition where system properties do not change over time",
      "transient: the period of change between steady states",
      "efficiency: ratio of useful output to total input (always less than 1 due to losses)",
      "redundancy: having backup systems for critical functions",
    ],
    commonMisconceptions: [
      "Stronger materials are not always better (stiffness, ductility, and toughness also matter)",
      "Safety factors are not arbitrary — they account for uncertainty, variability, and consequences of failure",
      "More complexity does not mean better design — the simplest solution that works is often best",
      "Analysis is necessary but insufficient — testing reveals what analysis misses",
      "Every design involves tradeoffs — there is no perfect solution, only optimal solutions given constraints",
    ],
    visualStrategy: "Use free body diagrams for mechanics, circuit diagrams for electrical systems, P&ID for process systems, stress-strain curves for materials, Bode plots for control systems, and CAD-style drawings for design. Always show both the ideal and the real (with tolerances, imperfections, and failure modes).",
    practiceStrategy: "Solve problems by drawing diagrams first. Build physical or virtual prototypes. Perform order-of-magnitude estimates before detailed calculations. Analyze real structures and systems (why is it designed this way?). Learn from failures — study engineering disasters and their root causes.",
    revisionStrategy: "Review by system type (structures, machines, circuits, processes). Re-derive key equations from first principles. Create design checklists for each domain. Study professional codes and standards. Analyze real products and reverse-engineer their design decisions.",
  },
};
