import type { SubjectProfile } from "../types";

export const financeProfile: SubjectProfile = {
  id: "finance",
  name: "Finance",
  description: "The study of managing money, investments, financial markets, and the allocation of capital across time and risk.",
  keywords: [
    "finance", "financial", "investing", "investment", "stock", "bond", "etf",
    "mutual fund", "index fund", "portfolio", "diversification", "asset allocation",
    "risk", "return", "volatility", "beta", "alpha", "sharpe ratio",
    "dividend", "yield", "interest", "compound interest", "present value",
    "future value", "discount rate", "net present value", "irr", "cash flow",
    "financial statement", "balance sheet", "income statement", "cash flow statement",
    "equity", "debt", "leverage", "margin", "liquidity", "solvency",
    "valuation", "dcf", "comparable analysis", "pe ratio", "eps",
    "market capitalization", "enterprise value", "ebitda",
    "option", "futures", "derivative", "hedge", "speculation",
    "bull market", "bear market", "recession", "inflation", "deflation",
    "monetary policy", "federal reserve", "central bank", "interest rate",
    "ipo", "merger", "acquisition", "private equity", "venture capital",
    "financial modeling", "budgeting", "forecasting", "financial planning",
  ],
  subdisciplines: [
    "corporate finance", "investments", "financial markets",
    "personal finance", "behavioral finance", "financial modeling",
    "portfolio management", "risk management", "derivatives",
    "fixed income", "international finance", "fintech",
  ],
  teachingPhilosophy: {
    coreBelief: "Finance should be taught concepts first, then formulas, then interpretation — building from fundamental intuition to sophisticated analysis.",
    explanationOrder: [
      "Introduce the financial concept or problem",
      "Build intuition through a personal finance parallel",
      "Present the formula and explain each term intuitively",
      "Calculate through a complete example",
      "Discuss interpretation: what does this number mean?",
      "Show real market examples",
      "Discuss limitations and common mistakes",
    ],
    preferredExamples: [
      "Retirement savings for compounding and time value of money",
      "Buying a house for mortgages and amortization",
      "Apple or Amazon stock for valuation",
      "2008 financial crisis for risk management",
      "Bitcoin for speculative bubbles and volatility",
      "Warren Buffett's portfolio for value investing",
    ],
    preferredAnalogies: [
      "Risk and return as a seesaw: higher potential returns require accepting more risk",
      "Diversification as not putting all eggs in one basket",
      "Compounding as a snowball rolling downhill",
      "Discounting as reversing compound interest",
      "Leverage as a magnifying glass: amplifies both gains and losses",
      "Market efficiency as a crowded room: hard to find bargains because everyone is looking",
    ],
    difficultyProgression: [
      "What financial problem does this solve?",
      "How would you explain it to someone managing their personal finances?",
      "What is the formula and what does each part mean?",
      "How do you interpret the result in a business context?",
      "What are the assumptions and limitations?",
      "How would a professional use this in practice?",
    ],
    responseStructure: [
      "Big Picture: the financial concept and why it matters",
      "Intuition: a personal finance analogy",
      "Core Explanation: the formula and methodology",
      "Worked Example: calculate through a real scenario",
      "Visual Thinking: charts, tables, or diagrams",
      "Common Mistakes: calculation errors and misinterpretations",
      "Memory Trick: remember the key formula or concept",
      "Real World Applications: market and business examples",
      "Challenge Question: a financial problem to analyze",
      "Summary: five key takeaways",
    ],
    importantTerminology: [
      "time value of money: a dollar today is worth more than a dollar tomorrow",
      "risk premium: the extra return investors demand for taking risk",
      "opportunity cost: the value of the next best alternative foregone",
      "liquidity: how quickly an asset can be converted to cash",
      "leverage: using borrowed money to amplify returns",
      "amortization: spreading a payment over time",
      "yield: the income return on an investment",
      "beta: a measure of how much a stock moves relative to the market",
    ],
    commonMisconceptions: [
      "Past performance does not guarantee future results",
      "Higher returns always come with higher risk (if it seems too good to be true, it is)",
      "Diversification does not eliminate risk, it reduces unsystematic risk",
      "A company's stock price is not the same as its value",
      "Debt is not always bad — leverage can amplify returns but also risk",
    ],
    visualStrategy: "Use line charts for price movements and trends, bar charts for comparisons, pie charts for portfolio allocation, waterfall charts for financial statements, S-curves for growth, bell curves for risk distributions, and tables for financial projections. Always label axes clearly and explain what the chart reveals.",
    practiceStrategy: "Build financial models in spreadsheets. Analyze real company financial statements. Calculate and interpret financial ratios. Simulate investment decisions and track outcomes. Read quarterly earnings reports and analyze the results before reading the market reaction.",
    revisionStrategy: "Create financial statement templates. Review by asset class (equities, fixed income, alternatives). Re-calculate valuations for different companies. Stay current with financial news. Practice explaining financial concepts to non-finance people.",
  },
};
