import type { SubjectProfile } from "../types";

export const generalScienceProfile: SubjectProfile = {
  id: "general-science",
  name: "General Science",
  description: "The systematic study of the natural and physical world through observation, experimentation, and evidence-based reasoning.",
  keywords: [
    "science", "scientific", "physics", "chemistry", "biology", "astronomy",
    "geology", "ecology", "climate", "environment", "evolution", "genetics",
    "cell", "molecule", "atom", "element", "compound", "reaction",
    "energy", "force", "motion", "wave", "light", "sound", "electromagnetism",
    "gravity", "quantum", "relativity", "thermodynamics", "nuclear",
    "organism", "species", "ecosystem", "photosynthesis", "respiration",
    "dna", "rna", "protein", "enzyme", "cell division", "natural selection",
    "chemical bond", "acid", "base", "ph", "oxidation", "reduction",
    "planet", "star", "galaxy", "solar system", "universe", "big bang",
    "experiment", "hypothesis", "theory", "law", "observation", "measurement",
    "variable", "control", "peer review", "reproducibility", "evidence",
    "scientific method", "induction", "deduction", "falsifiability",
  ],
  subdisciplines: [
    "physics", "chemistry", "biology", "astronomy", "geology",
    "ecology", "neuroscience", "genetics", "materials science",
    "environmental science", "oceanography", "meteorology",
  ],
  teachingPhilosophy: {
    coreBelief: "Science should be taught as a process of discovery — how we know what we know through experiments, evidence, and reasoning, not just what we know.",
    explanationOrder: [
      "Start with an observation or question about the natural world",
      "Explore what we might intuitively expect before revealing the science",
      "Design a thought experiment or real experiment",
      "Present the scientific explanation with evidence",
      "Show how this connects to other scientific concepts",
      "Discuss what we still do not know",
      "Explain the real-world implications",
    ],
    preferredExamples: [
      "The apple falling for gravity and Newton's laws",
      "Boiling water for phase changes and thermodynamics",
      "The night sky for astronomy and cosmology",
      "The human body for biology and physiology",
      "Cooking for chemistry (chemical reactions in food)",
      "The weather for atmospheric science and chaos theory",
    ],
    preferredAnalogies: [
      "The scientific method as detective work: gathering clues, testing hypotheses, building a case",
      "Evolution as a blind watchmaker: design without a designer",
      "Energy as money: can be converted between forms but not created or destroyed",
      "Entropy as a messy room: systems naturally become more disordered over time",
      "Atoms as LEGO bricks: a limited set of building blocks creating infinite complexity",
    ],
    difficultyProgression: [
      "What natural phenomenon does this explain?",
      "What is the basic mechanism?",
      "What experiments support this theory?",
      "How does this theory make testable predictions?",
      "What are the limitations of the current model?",
      "What open questions remain?",
    ],
    responseStructure: [
      "Big Picture: the scientific concept and why it matters",
      "Intuition: everyday observation that illustrates it",
      "Core Explanation: the science with evidence",
      "Worked Example: applying the concept to understand a phenomenon",
      "Visual Thinking: diagrams, charts, or illustrations",
      "Common Mistakes: misconceptions in popular understanding",
      "Memory Trick: key facts and relationships",
      "Real World Applications: technology and everyday life",
      "Challenge Question: design an experiment or predict an outcome",
      "Summary: five key scientific points",
    ],
    importantTerminology: [
      "hypothesis: a testable prediction about the natural world",
      "theory: a well-substantiated explanation supported by evidence",
      "law: a concise description of a consistent natural phenomenon",
      "variable: a factor that can change in an experiment",
      "control: a standard of comparison in an experiment",
      "peer review: evaluation of scientific work by other experts",
      "falsifiability: the capacity of a theory to be proven wrong",
      "consilience: the principle that evidence from independent sources converges on the same conclusion",
    ],
    commonMisconceptions: [
      "A theory in science is not a guess — it is a well-tested explanation supported by massive evidence",
      "Science does not prove anything absolutely — it builds increasingly reliable models",
      "Correlation does not imply causation — this is the most common error in interpreting data",
      "Natural is not better — many natural substances are toxic, many synthetic ones are safe",
      "Science is not a collection of facts — it is a process of continual questioning and refinement",
    ],
    visualStrategy: "Use diagrams for processes (photosynthesis, the water cycle), charts for data and relationships, timelines for discoveries, flowcharts for experimental procedures, scales for magnitudes (atomic to cosmic), and cross-sections for structures (cells, Earth, stars). Show before/after comparisons for experimental results.",
    practiceStrategy: "Ask 'what would happen if' questions and reason through the answer. Design experiments to test hypotheses before looking up the answer. Replicate classic experiments mentally. Distinguish correlation from causation in news articles. Calculate order-of-magnitude estimates using scientific principles.",
    revisionStrategy: "Review by scale (atomic, molecular, cellular, organism, planetary, cosmic). Connect concepts across disciplines (how chemistry explains biology, how physics explains chemistry). Teach scientific concepts to non-scientists. Read popular science to see concepts applied to current research.",
  },
};
