import type { SubjectProfile } from "../types";

export const historyProfile: SubjectProfile = {
  id: "history",
  name: "History",
  description: "The study of past events, societies, cultures, and the forces that have shaped the human experience across time.",
  keywords: [
    "history", "historical", "ancient", "medieval", "modern", "century",
    "civilization", "empire", "kingdom", "republic", "revolution",
    "war", "battle", "treaty", "alliance", "colonization", "independence",
    "monarchy", "democracy", "dictatorship", "republic", "parliament",
    "economy", "trade", "agriculture", "industrialization", "technology",
    "culture", "religion", "philosophy", "art", "literature", "science",
    "society", "class", "gender", "race", "slavery", "civil rights",
    "exploration", "discovery", "migration", "urbanization",
    "primary source", "secondary source", "historiography", "archive",
    "timeline", "period", "era", "epoch", "dynasty", "reign",
    "cold war", "world war", "civil war", "independence movement",
    "renaissance", "enlightenment", "reformation", "industrial revolution",
    "feudalism", "capitalism", "socialism", "communism", "imperialism",
    "nationalism", "globalization", "diplomacy", "geopolitics",
  ],
  subdisciplines: [
    "ancient history", "medieval history", "early modern history",
    "modern history", "military history", "economic history",
    "cultural history", "social history", "political history",
    "diplomatic history", "intellectual history", "world history",
    "art history", "history of science", "historiography",
  ],
  teachingPhilosophy: {
    coreBelief: "History should be taught as a web of causation, not a list of dates — understanding why events happened, how they connect, and what we can learn from them.",
    explanationOrder: [
      "Set the context: what was the world like before this event?",
      "Identify the key forces and actors involved",
      "Present the narrative of what happened",
      "Analyze the causes (immediate and underlying)",
      "Examine the consequences and legacy",
      "Discuss different historical interpretations",
      "Connect to broader patterns and today's world",
    ],
    preferredExamples: [
      "The fall of Rome for understanding civilizational decline",
      "World War I for the unintended consequences of alliances",
      "The Civil Rights Movement for social change strategies",
      "The Industrial Revolution for technological transformation",
      "The Renaissance for cultural and intellectual rebirth",
      "Decolonization for the end of empires",
    ],
    preferredAnalogies: [
      "History as a river: multiple currents flowing together, sometimes merging, sometimes diverging",
      "Primary sources as eyewitness testimony: valuable but biased",
      "Historical interpretation as detective work: assembling evidence to reconstruct what happened",
      "Cause and effect in history as a row of dominoes vs. a spiderweb",
      "Periodization as drawing lines on a map: useful but artificial",
    ],
    difficultyProgression: [
      "What happened? (basic narrative)",
      "Why did it happen? (causation)",
      "What were the consequences? (significance)",
      "How do historians interpret this differently? (historiography)",
      "What patterns does this reveal? (comparison)",
      "What lessons does this hold for the present? (relevance)",
    ],
    responseStructure: [
      "Big Picture: the historical event or period and its significance",
      "Intuition: the human story behind the history",
      "Core Explanation: the narrative with key details",
      "Worked Example: analyzing a primary source or specific case",
      "Visual Thinking: timelines, maps, or diagrams",
      "Common Mistakes: anachronisms and oversimplifications",
      "Memory Trick: remember the key dates or sequence",
      "Real World Applications: connections to current events",
      "Challenge Question: analyze a source or interpret an event",
      "Summary: five essential points",
    ],
    importantTerminology: [
      "primary source: firsthand account or document from the period",
      "secondary source: scholarly analysis based on primary sources",
      "historiography: the study of how history has been written and interpreted",
      "anachronism: attributing modern ideas or values to past societies",
      "contingency: the idea that events could have unfolded differently",
      "periodization: dividing history into distinct periods for analysis",
      "causation: the relationship between events where one leads to another",
      "teleology: interpreting history as progressing toward a predetermined end",
    ],
    commonMisconceptions: [
      "History is not a list of dates to memorize — it is analysis of causation and change",
      "Primary sources are not objective truth — every source has a perspective and bias",
      "History is not written by the victors alone — there are always multiple perspectives",
      "The past is a foreign country — judging historical figures by modern standards is anachronistic",
      "History does not repeat itself, but patterns and lessons can be drawn",
    ],
    visualStrategy: "Use timelines for chronological understanding, maps for geographical context, family trees for dynasties and relationships, flow charts for causation, tables for comparing civilizations or periods, and diagrams for social structures. Annotated maps that show change over time are especially powerful.",
    practiceStrategy: "Analyze primary sources before reading secondary interpretations. Create timelines connecting events across regions. Write historical arguments using evidence. Compare different historians' interpretations of the same event. Draw connections between historical patterns and current events.",
    revisionStrategy: "Review by region and period, then by theme (war, trade, ideas). Create mental timelines. Compare and contrast different civilizations at the same point in time. Practice writing thesis statements with supporting evidence. Teach historical narratives to others.",
  },
};
