import type { SubjectProfile } from "../types";

export const lawProfile: SubjectProfile = {
  id: "law",
  name: "Law",
  description: "The system of rules, principles, and institutions that govern society, resolve disputes, and uphold rights and justice.",
  keywords: [
    "law", "legal", "statute", "regulation", "contract", "tort", "criminal",
    "civil", "constitutional", "jurisdiction", "precedent", "case law",
    "common law", "civil law", "statutory interpretation", "litigation",
    "plaintiff", "defendant", "prosecution", "defense", "appeal",
    "verdict", "judgment", "ruling", "opinion", "holding", "dicta",
    "brief", "motion", "discovery", "deposition", "evidence",
    "burden of proof", "standard of review", "due process", "equal protection",
    "first amendment", "fourth amendment", "fifth amendment", "fourteenth amendment",
    "negligence", "breach", "damages", "injunction", "specific performance",
    "consideration", "offer", "acceptance", "void", "voidable",
    "treaty", "international law", "human rights", "sovereignty",
    "property law", "intellectual property", "copyright", "trademark", "patent",
    "corporate law", "securities", "antitrust", "bankruptcy",
    "jurisprudence", "legal reasoning", "irac", "legal writing",
  ],
  subdisciplines: [
    "constitutional law", "criminal law", "contract law", "tort law",
    "property law", "civil procedure", "criminal procedure", "evidence",
    "corporate law", "tax law", "international law", "human rights law",
    "environmental law", "intellectual property law", "labor law",
    "family law", "admiralty law", "legal philosophy",
  ],
  teachingPhilosophy: {
    coreBelief: "Law should be taught through principles first, then statutes, then cases, then application, then counterarguments — building from foundational reasoning to complex analysis.",
    explanationOrder: [
      "State the legal principle or rule",
      "Explain the rationale behind it (why does this rule exist?)",
      "Present the governing statute or source of law",
      "Illustrate with a landmark case (facts, holding, reasoning)",
      "Apply the rule to a new hypothetical",
      "Present counterarguments and alternative approaches",
      "Discuss exam strategy and common pitfalls",
    ],
    preferredExamples: [
      "Famous Supreme Court cases that define the area",
      "Everyday hypotheticals that illustrate the rule",
      "Recent cases showing the law in modern context",
      "Fact patterns that test the boundaries of the rule",
      "Comparative examples from different jurisdictions",
    ],
    preferredAnalogies: [
      "Law as the rules of a game: defining what is allowed and the consequences",
      "Precedent as following the path others have carved",
      "Statutory interpretation as following a recipe with unclear instructions",
      "Burden of proof as the weight on a scale that must tip",
      "Contract as a promise the law will enforce",
    ],
    difficultyProgression: [
      "What is the rule and why does it exist?",
      "How does the rule apply in simple facts?",
      "How do courts interpret ambiguous language?",
      "What happens when rules conflict?",
      "How do exceptions and defenses work?",
      "How do you argue both sides effectively?",
    ],
    responseStructure: [
      "Big Picture: the legal area and why it matters",
      "Intuition: the core principle in plain language",
      "Core Explanation: the rule or doctrine with authority",
      "Worked Example: IRAC analysis of a fact pattern",
      "Visual Thinking: a flowchart or comparison table",
      "Common Mistakes: errors in legal reasoning or exam strategy",
      "Memory Trick: key elements to remember",
      "Real World Applications: how this affects everyday life or business",
      "Challenge Question: apply the law to a new scenario",
      "Summary: five essential points",
    ],
    importantTerminology: [
      "stare decisis: let the decision stand — follow precedent",
      "jurisdiction: a court's authority to hear a case",
      "holding: the court's decision on a specific issue",
      "dicta: statements in an opinion that are not binding precedent",
      "burden of proof: the obligation to prove allegations (preponderance, clear and convincing, beyond reasonable doubt)",
      "standing: the right to bring a lawsuit based on personal injury",
      "remand: send a case back to a lower court for further proceedings",
      "en banc: hearing by the full panel of appellate judges",
    ],
    commonMisconceptions: [
      "Law is not about memorizing every statute — it is about reasoning from principles",
      "Precedent is binding, but courts can distinguish or overrule",
      "There is rarely one 'right' answer — good lawyers argue both sides",
      "The law is not static; it evolves through interpretation and legislation",
      "Statutory language is often ambiguous by design or necessity",
    ],
    visualStrategy: "Use flowcharts for legal analysis (elements of a claim, procedural steps), tables for comparing jurisdictions or cases, timelines for procedural history, decision trees for legal tests (balancing tests, multi-factor tests), and concept maps showing relationships between legal doctrines.",
    practiceStrategy: "Practice IRAC (Issue, Rule, Application, Conclusion) for every topic. Write practice exam answers under time pressure. Argue both sides of every issue. Brief cases using the standard format (facts, issue, holding, reasoning, significance). Analyze hypotheticals before looking at model answers.",
    revisionStrategy: "Create attack outlines organized by elements of each cause of action. Use flowcharts to map procedural steps. Review by comparing and contrasting similar doctrines. Practice spotting issues in complex fact patterns. Teach rules to peers to solidify understanding.",
  },
};
