import type { SubjectProfile } from "../types";

export const mathematicsProfile: SubjectProfile = {
  id: "mathematics",
  name: "Mathematics",
  description: "The study of numbers, quantities, shapes, patterns, and the logical relationships between them.",
  keywords: [
    "algebra", "calculus", "geometry", "trigonometry", "statistics", "probability",
    "linear algebra", "differential equation", "discrete math", "number theory",
    "set theory", "topology", "analysis", "logic", "proof", "theorem",
    "equation", "function", "derivative", "integral", "limit", "series",
    "matrix", "vector", "eigenvalue", "transformation", "space",
    "distribution", "variance", "correlation", "hypothesis", "regression",
    "combinatorics", "graph theory", "optimization", "modulo",
    "axiom", "lemma", "corollary", "conjecture", "isomorphism",
    "polynomial", "logarithm", "exponential", "trigonometric",
    "fraction", "decimal", "percentage", "ratio", "proportion",
    "prime", "factor", "multiple", "divisor", "remainder",
  ],
  subdisciplines: [
    "algebra", "calculus", "geometry", "statistics", "probability",
    "linear algebra", "differential equations", "discrete mathematics",
    "number theory", "real analysis", "complex analysis", "topology",
    "combinatorics", "graph theory", "optimization", "numerical analysis",
  ],
  teachingPhilosophy: {
    coreBelief: "Mathematics must be taught through intuition before notation. Every formula should be derived, not memorized. Students should understand why before how.",
    explanationOrder: [
      "Start with the real-world problem that motivated this math",
      "Build intuition through a concrete example",
      "Show the visual or geometric interpretation",
      "Derive the formula step by step",
      "State the formal definition only after intuition is built",
      "Work through multiple examples with increasing difficulty",
      "Connect to previously learned concepts",
      "Show common errors and why they happen",
    ],
    preferredExamples: [
      "Falling objects for derivatives (instantaneous rate of change)",
      "Area under a curve for integrals",
      "Shopping discounts for percentages",
      "Map navigation for geometry",
      "Population growth for exponential functions",
      "Gambling and insurance for probability",
    ],
    preferredAnalogies: [
      "Derivatives as speedometers: measuring instantaneous change",
      "Integrals as odometers: accumulating total change",
      "Matrices as transformation machines: mapping inputs to outputs",
      "Probability as measuring uncertainty: how likely is an outcome",
      "Proofs as legal arguments: establishing truth through logical steps",
      "Functions as vending machines: input in, output out",
    ],
    difficultyProgression: [
      "What real situation does this describe?",
      "Can you draw it?",
      "What pattern do you notice?",
      "Can you express that pattern with symbols?",
      "What happens when you generalize?",
      "Can you prove it always works?",
    ],
    responseStructure: [
      "Big Picture: what this concept describes in the real world",
      "Intuition: an everyday analogy or visual",
      "Core Explanation: the formal concept with derivation",
      "Worked Example: step-by-step computation",
      "Visual Thinking: geometric or graphical interpretation",
      "Common Mistakes: typical errors and misconceptions",
      "Memory Trick: remember the formula or approach",
      "Real World Applications: where this math is used",
      "Challenge Question: a problem to solve",
      "Summary: five key points",
    ],
    importantTerminology: [
      "function: a rule that maps each input to exactly one output",
      "derivative: the instantaneous rate of change of a function",
      "integral: the accumulated area under a curve",
      "limit: the value a function approaches as input approaches some value",
      "vector: a quantity with both magnitude and direction",
      "matrix: a rectangular array of numbers representing a transformation",
      "probability: a measure of how likely an event is to occur",
      "proof: a logical argument establishing truth beyond doubt",
    ],
    commonMisconceptions: [
      "Mathematics is not about memorization — it is about logical reasoning",
      "Being 'bad at math' is usually about missing foundational concepts, not ability",
      "Getting the right answer is less important than understanding the process",
      "Proofs are not optional — they are the foundation of all mathematical knowledge",
      "Intuition and rigor are complementary, not opposing forces",
    ],
    visualStrategy: "Use graphs and plots for functions and their transformations, geometric diagrams for algebra, area models for multiplication and probability, tree diagrams for probability and counting, number lines for operations, coordinate systems for geometry, and flowcharts for proofs and derivations. Always connect the visual to the symbolic representation.",
    practiceStrategy: "Practice through progressive problem sets: start with recognition (identify the concept), then application (use the formula), then adaptation (modify the approach), then creation (design a solution). Use spaced repetition for fundamentals. Derive formulas from memory periodically.",
    revisionStrategy: "Create a concept map connecting all topics. Re-derive key formulas from first principles. Teach concepts to someone else. Solve problems from previous topics to maintain connections. Focus on the 'why' behind each technique, not just the 'how'.",
  },
};
