import type { SubjectProfile } from "../types";

export const writingProfile: SubjectProfile = {
  id: "writing",
  name: "Writing",
  description: "The craft of expressing ideas through written language with clarity, purpose, structure, and style for different audiences and genres.",
  keywords: [
    "writing", "writing", "essay", "article", "blog", "content", "copy",
    "creative writing", "academic writing", "technical writing", "business writing",
    "fiction", "non-fiction", "poetry", "script", "screenplay",
    "grammar", "punctuation", "syntax", "sentence structure", "paragraph",
    "thesis", "argument", "evidence", "analysis", "synthesis",
    "narrative", "voice", "tone", "style", "genre", "audience", "purpose",
    "edit", "revise", "proofread", "rewrite", "draft", "outline",
    "hook", "thesis statement", "topic sentence", "transition", "conclusion",
    "metaphor", "simile", "imagery", "symbolism", "dialogue", "description",
    "plot", "character", "setting", "theme", "conflict", "resolution",
    "active voice", "passive voice", "show don't tell", "word choice",
    "citation", "reference", "bibliography", "plagiarism", "paraphrase",
    "rhetoric", "persuasion", "ethos", "pathos", "logos",
  ],
  subdisciplines: [
    "creative writing", "academic writing", "technical writing",
    "business writing", "journalism", "content writing",
    "fiction writing", "non-fiction writing", "poetry",
    "screenwriting", "copywriting", "essay writing",
  ],
  teachingPhilosophy: {
    coreBelief: "Writing should be taught as thinking made visible — structure, clarity, and revision are the keys to effective communication in any genre.",
    explanationOrder: [
      "Define the purpose and audience for the writing",
      "Establish the core message or thesis",
      "Outline the structure before writing",
      "Write a complete draft without editing",
      "Revise for structure and argument",
      "Edit for clarity and concision",
      "Proofread for mechanics",
    ],
    preferredExamples: [
      "Famous essays for structure and argument",
      "Great novels for narrative technique",
      "News articles for concise communication",
      "Scientific papers for clear exposition",
      "Advertising copy for persuasion",
      "Letters and emails for practical writing",
      "Before and after revisions that show improvement",
    ],
    preferredAnalogies: [
      "Writing as architecture: a blueprint (outline) before construction (drafting)",
      "Revision as sculpting: removing excess to reveal the form within",
      "Paragraphs as building blocks: each serves a distinct purpose in the larger structure",
      "Transitions as bridges: connecting one idea to the next",
      "Active voice as a handshake: direct, clear, confident",
    ],
    difficultyProgression: [
      "What are you trying to say? (message)",
      "Who are you saying it to? (audience)",
      "How will you organize it? (structure)",
      "How do you say it clearly? (style)",
      "How do you make it memorable? (voice)",
      "How do you refine it? (revision)",
    ],
    responseStructure: [
      "Big Picture: the writing concept and why it matters for communication",
      "Intuition: the idea in practice",
      "Core Explanation: principles and techniques",
      "Worked Example: before and after comparison",
      "Visual Thinking: outlines, diagrams, or comparison tables",
      "Common Mistakes: what weakens writing",
      "Memory Trick: the key rule or heuristic",
      "Real World Applications: where this writing skill is used",
      "Challenge Question: improve or analyze a piece of writing",
      "Summary: five essential writing principles",
    ],
    importantTerminology: [
      "thesis: the central claim or argument of a piece of writing",
      "voice: the distinctive style and personality of the writer",
      "tone: the attitude conveyed through word choice and style",
      "show don't tell: using concrete details instead of abstract statements",
      "active voice: the subject performs the action (clear and direct)",
      "passive voice: the subject receives the action (often weaker)",
      "transition: a word or phrase that connects ideas",
      "revision: re-seeing the work to improve content and structure",
    ],
    commonMisconceptions: [
      "Great writing is not born, it is rewritten — first drafts are meant to be bad",
      "Using big words does not make writing better — clarity is the highest goal",
      "Grammar rules are tools, not chains — effective communication comes first",
      "Writing is not a talent you either have or don't — it is a skill developed through practice",
      "The best writing is invisible — the reader notices the ideas, not the words",
    ],
    visualStrategy: "Use outlines showing hierarchical structure, paragraph maps showing topic sentence and supporting details, before/after revision examples, comparison tables for different genres or styles, and diagrams showing the relationship between thesis, arguments, and evidence.",
    practiceStrategy: "Write every day, even if just a paragraph. Read widely across genres. Imitate styles you admire to understand technique. Practice specific skills (writing hooks, transitions, descriptions). Revise old work to see improvement. Get feedback and apply it.",
    revisionStrategy: "Create checklists for different types of writing. Practice the four stages: outline, draft, revise, proofread. Read your work aloud (catches awkward phrasing). Study writers whose style you admire. Build a personal style guide of rules and preferences.",
  },
};
