declare module "lucide-react" {
  import type { FC, SVGProps } from "react";
  type Icon = FC<SVGProps<SVGSVGElement> & { size?: number; strokeWidth?: number }>;
  export const Sparkles: Icon; export const FileText: Icon; export const ArrowRight: Icon;
  export const X: Icon; export const Loader2: Icon; export const BookMarked: Icon;
  export const CalendarClock: Icon; export const Download: Icon; export const Search: Icon;
  export const Upload: Icon; export const Copy: Icon; export const Check: Icon;
  export const Menu: Icon; export const ChevronRight: Icon; export const ChevronLeft: Icon;
  export const Plus: Icon; export const Minus: Icon; export const Trash2: Icon;
  export const Edit3: Icon; export const ExternalLink: Icon; export const BookOpen: Icon;
  export const Lightbulb: Icon; export const AlertCircle: Icon; export const Settings: Icon;
  export const Maximize2: Icon; export const Minimize2: Icon; export const PanelLeft: Icon;
  export const PanelRight: Icon; export const Globe: Icon; export const Brain: Icon;
  export const Network: Icon; export const Layers: Icon; export const List: Icon;
  export const RefreshCw: Icon; export const Zap: Icon; export const User: Icon;
  export const Bell: Icon; export const Bookmark: Icon; export const Share2: Icon;
  export const RotateCw: Icon; export const Undo2: Icon; export const Redo2: Icon;
  export const PenTool: Icon; export const Move: Icon; export const ZoomIn: Icon;
  export const ZoomOut: Icon; export const Columns: Icon; export const Layout: Icon;
  export const Palette: Icon; export const Monitor: Icon; export const Moon: Icon;
  export const Sun: Icon; export const Command: Icon; export const Keyboard: Icon;
  export const Terminal: Icon; export const MessageSquare: Icon; export const Send: Icon;
  export const Play: Icon; export const Pause: Icon; export const Home: Icon;
  export const LogOut: Icon; export const LogIn: Icon; export const Sliders: Icon;
  export const Filter: Icon; export const MoreHorizontal: Icon; export const MoreVertical: Icon;
  export const Star: Icon; export const Clock: Icon; export const Target: Icon;
  export const Flag: Icon; export const Folder: Icon; export const File: Icon;
  export const BarChart3: Icon; export const PieChart: Icon; export const TrendingUp: Icon;
  export const Sidebar: Icon; export const Fullscreen: Icon; export const Quote: Icon;
  export const Code: Icon; export const Bold: Icon; export const Italic: Icon;
  export const ListOrdered: Icon; export const Hash: Icon; export const Image: Icon;
  export const Link: Icon; export const Type: Icon; export const Grid3X3: Icon;
  export const Eraser: Icon; export const Heading1: Icon; export const Heading2: Icon;
  export const Tag: Icon; export const FileEdit: Icon; export const Archive: Icon;
  export const Key: Icon; export const FileDown: Icon; export const Info: Icon;
  export const Github: Icon; export const ArrowLeft: Icon; export const BookText: Icon;
  export const BrainCircuit: Icon; export const HelpCircle: Icon; export const Atom: Icon;
  export const FlaskConical: Icon; export const Library: Icon; export const MicOff: Icon;
  export const WifiOff: Icon; export const Users: Icon; export const Building2: Icon;
  export const MapPin: Icon; export const GitBranch: Icon;
  export const ShieldCheck: Icon;
  export const ChevronDown: Icon;
  export const Shield: Icon;
  export const GraduationCap: Icon;
  export const Globe2: Icon;
  export const Code2: Icon;
  export const Beaker: Icon;
  export const Calculator: Icon;
  export const Scale: Icon;
  export const DollarSign: Icon;
  export const HeartPulse: Icon;
  export const ArrowUpRight: Icon;
  export const FolderOpen: Icon;
  export const FolderPlus: Icon;
  export const Pencil: Icon;
  export const Pin: Icon;
  export const CheckCircle2: Icon;
  export const Cloud: Icon;
  export const CloudOff: Icon;
  export const Activity: Icon;
  export const Cpu: Icon;
  export const UploadCloud: Icon;
  export const SearchX: Icon;
  export const StickyNote: Icon;
  export const Workflow: Icon;
  export const History: Icon;
  export const Presentation: Icon;
}
